apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-deployment
      tier: backend
      track: stable
  replicas: 5
  template:
    metadata:
      labels:
        app: api-deployment
        tier: backend
        track: stable
    spec:
      containers:
        - name: app-backend-api
          image: "eu.gcr.io/kubernetes-practice-199508/api-image"
          ports:
            - containerPort: 5000

 