version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/react-app

    steps:
      - checkout
      - run:
          name: list contents of pwd
          command: ls


      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "bucketlist-react/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
    working_directory: ~/react-app/bucketlist-react
      - run:
          name: install dependencies
          command: |
            npm install
            gulp sass
  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "bucketlist/package.json" }}  

   
      # run tests!
      - run: npm test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test

