version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/react-app

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run:
          name: install gulp cli
          command: |
            sudo npm install --global gulp-cli

      - run:
          name: install dependencies
          command: |
            npm install
            
      - run:
          name: compile sass
          command: |
            gulp sass
  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}  

      # run tests!
      - run:
          name: run tests
          command: |
            npm test

  build-docker-image:
    docker:
      - image: circleci/ubuntu

    steps:
       - run:
           name: install docker
           command: |
             apt-get update && apt-get install docker-ce





workflows:
  version: 2
  build_and_test:
    jobs:
      - build-docker-image
      - build-test


