version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/react-app

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - run:
          name: install gulp cli
          command: |
            sudo npm install --global gulp-cli

      - run:
          name: install dependencies
          command: |
            npm install
            
      - run:
          name: compile sass
          command: |
            gulp sass
  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}  

      # run tests!
      - run:
          name: run tests
          command: |
            npm test

  build-docker-image:
    docker:
      - image: ubuntu:16.04

    steps:
       - checkout

       - run:
            name: add user david to docker group
            command: |
              apt-get update
              apt-get install -y sudo curl
              # sudo useradd david
              
              

       - run:
           name: install docker
           command: |
              curl -fsSL get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              # sudo groupadd docker
              sudo usermod -aG docker root
              # sudo service docker start
              sudo docker build -t mukiibi:frontend . 
              sudo docker tag mukiibi:frontend mukiibi/frontend
              sudo docker push mukiibi/frontend






workflows:
  version: 2
  build_and_test:
    jobs:
      - build-test
      - build-docker-image:
          requires:
            - build-test


