language: python

python:
  - 3.6

before_install:
  - pip install -r requirements.txt

services:
  - postgresql

env:
  global:
    - DATABASE_URL=postgresql://localhost/bucketlist_testdb
    - APP_SECRET=iigMnxy7y7dFJppmd3JgZRzOUYLgmjaXX 
    - REQUESTS_ORIGIN="*"
    - TEST_DATABASE_URL=postgresql://localhost/bucketlist_testdb

before_script:
  - psql -c 'create database bucketlist_testdb;' -U postgres

script:
  - nosetests --with-coverage --cover-package=bucketlist

after_success: coveralls
